# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='fields',
            field=models.CharField(choices=[('resi', 'Residential'), ('land', 'Land'), ('comm', 'Commercial')], default='buy', max_length=9),
        ),
        migrations.AddField(
            model_name='information',
            name='option',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='buy', max_length=9),
        ),
    ]
